/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface TipFacetInterface extends utils.Interface {
  functions: {};

  events: {
    "Donate(address,address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Donate"): EventFragment;
}

export interface DonateEventObject {
  donator: string;
  addressToDonate: string;
  tokenAddress: string;
  tokenAmount: BigNumber;
}
export type DonateEvent = TypedEvent<
  [string, string, string, BigNumber],
  DonateEventObject
>;

export type DonateEventFilter = TypedEventFilter<DonateEvent>;

export interface TipFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TipFacetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "Donate(address,address,address,uint256)"(
      donator?: PromiseOrValue<string> | null,
      addressToDonate?: PromiseOrValue<string> | null,
      tokenAddress?: null,
      tokenAmount?: null
    ): DonateEventFilter;
    Donate(
      donator?: PromiseOrValue<string> | null,
      addressToDonate?: PromiseOrValue<string> | null,
      tokenAddress?: null,
      tokenAmount?: null
    ): DonateEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
