version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tipdapp
      POSTGRES_HOST_AUTH: trust
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgressql/data
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
volumes:
  db:
