import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>CryptoTip</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      Hello
    </div>
  );
}

Home.getLayout = (page: JSX.Element): JSX.Element => <>{page}</>;

Home.isProtected = true;
