import { useSelector, useDispatch } from 'react-redux';
import { useEffect } from 'react';

import Head from 'next/head';
import Image from 'next/image';

import { login } from '../src/redux/userSlice';
import { EthersProvider } from 'src/hooks/useEthers';
import { Toaster } from 'react-hot-toast';

export default function Home() {
  // const dispatch = useDispatch();

  // useEffect(() => {
  //   dispatch(login({ email: 'jannowak@gmail.com', password: 'haslo123' }));
  // }, []);

  return (
    <div>
      <Head>
        <title>CryptoTip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

Home.getLayout = (page) => (
  // <Provider store={store}>
    <EthersProvider>
      <Toaster position="top-center" reverseOrder={false} />
      {page}
    </EthersProvider>
  // </Provider>
);
